version: '3'

services:
  mysql:
    image: mysql:8.0.31
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - 3307:3306
    expose:
<<<<<<< HEAD
      - 3307
=======
      - 3306
    environment:
      - MYSQL_DATABASE=Lockerit
      - MYSQL_USER=locker
      - MYSQL_PASSWORD=Lockerit!
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
>>>>>>> d973dd3ce88fa008b8a20ef6ae43feded9ff61eb
    env_file:
      - mysql.env
    networks:
      - internalnet

  node:
    build: .
    image: lockerit:1
    command: npm run dev
    volumes:
      - ./code/:/app/code/
    ports:
      - 3000:3000
    #   - ./src:/lockey
    #   - ./package.json:/lockey/package.json
    # working_dir: /lockey
    # command: sh -c 'npm install && npm start'
    expose:
      - 3000
    depends_on:
      - mysql
    networks:
      - internalnet
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=locker
      - MYSQL_PASSWORD=Lockerit!
      - MYSQL_DATABASE=Lockerit
      - SERVICE_TAGS=dev
      - SERVICE_NAME=lockey
      - SERVER_PORT=3000
      - NODE_ENV=development
      - DEBUG=lockerit:*

networks:
  internalnet:
    driver: bridge
volumes:
  myapp_data: