version: '3'

services:
  mysql-development:
    image: mysql:8.0.31
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: lockerit
      MYSQL_USER: lockerit_user
      MYSQL_PASSWORD: 1q.2w3e4r
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      # just for first time
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql

  node-development:
    image: node:18.12.1-alpine3.15
    depends_on:
      - mysql-development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm start"