-- MySQL Script generated by MySQL Workbench
-- Sun Nov 27 20:18:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Lockerit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lockerit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lockerit` DEFAULT CHARACTER SET utf8 ;
USE `Lockerit` ;

-- -----------------------------------------------------
-- Table `Lockerit`.`tipoEnvio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`tipoEnvio` (
  `id_tipoEnvio` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipoEnvio` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipoEnvio`),
  UNIQUE INDEX `id_tipoEnvio_UNIQUE` (`id_tipoEnvio` ASC) VISIBLE,
  UNIQUE INDEX `nombre_tipoEnvio_UNIQUE` (`nombre_tipoEnvio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`tipoUsuario` (
  `id_tipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipoUsuario`),
  UNIQUE INDEX `id_tipoUsuario_UNIQUE` (`id_tipoUsuario` ASC) VISIBLE,
  UNIQUE INDEX `nombre_tipoUsuario_UNIQUE` (`nombre_tipoUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(60) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `numeroCelular` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `id_tipoUsuario` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  CONSTRAINT `id_tipoUsuario`
    FOREIGN KEY (`id_tipoUsuario`)
    REFERENCES `Lockerit`.`tipoUsuario` (`id_tipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`Empleados` (
  `numeroEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(60) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `numeroCelular` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `id_tipoUsuario` INT NOT NULL,
  PRIMARY KEY (`numeroEmpleado`),
  UNIQUE INDEX `numeroEmpleado_UNIQUE` (`numeroEmpleado` ASC) VISIBLE,
  CONSTRAINT `tipoUsuario`
    FOREIGN KEY (`id_tipoUsuario`)
    REFERENCES `Lockerit`.`tipoUsuario` (`id_tipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`Tamanio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`Tamanio` (
  `id_tamanio` INT NOT NULL AUTO_INCREMENT,
  `nombre_tamaño` VARCHAR(25) NOT NULL,
  `alto` FLOAT NOT NULL,
  `ancho` FLOAT NOT NULL,
  `profundidad` FLOAT NOT NULL,
  PRIMARY KEY (`id_tamanio`),
  UNIQUE INDEX `id_tipoPaquete_UNIQUE` (`id_tamanio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`estadoEnvio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`estadoEnvio` (
  `id_estadoEnvio` INT NOT NULL AUTO_INCREMENT,
  `nombre_estadoEnvio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estadoEnvio`),
  UNIQUE INDEX `id_estadoEnvio_UNIQUE` (`id_estadoEnvio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`Alcaldias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`Alcaldias` (
  `id_Alcaldias` INT NOT NULL AUTO_INCREMENT,
  `nombre_alcaldia` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_Alcaldias`),
  UNIQUE INDEX `id_Alcaldias_UNIQUE` (`id_Alcaldias` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`Locker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`Locker` (
  `id_locker` INT NOT NULL AUTO_INCREMENT,
  `nombre_locker` VARCHAR(60) NOT NULL,
  `ancho` FLOAT NOT NULL,
  `alto` FLOAT NOT NULL,
  `profundidad` FLOAT NOT NULL,
  `num_taquillasS` INT NOT NULL,
  `num_taquillasM` INT NOT NULL,
  `num_taquillasL` INT NOT NULL,
  `ubicacion` VARCHAR(250) NOT NULL,
  `id_alcaldia` INT NULL,
  `estado_locker` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_locker`),
  UNIQUE INDEX `id_locker_UNIQUE` (`id_locker` ASC) VISIBLE,
  CONSTRAINT `alcaldia`
    FOREIGN KEY (`id_alcaldia`)
    REFERENCES `Lockerit`.`Alcaldias` (`id_Alcaldias`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`Taquilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`Taquilla` (
  `id_taquilla` INT NOT NULL AUTO_INCREMENT,
  `id_tamanio` INT NOT NULL,
  `id_locker` INT NULL,
  `estado_taquilla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_taquilla`),
  UNIQUE INDEX `id_taquilla_UNIQUE` (`id_taquilla` ASC) VISIBLE,
  CONSTRAINT `tamanio`
    FOREIGN KEY (`id_tamanio`)
    REFERENCES `Lockerit`.`Tamanio` (`id_tamanio`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `locker`
    FOREIGN KEY (`id_locker`)
    REFERENCES `Lockerit`.`Locker` (`id_locker`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`metodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`metodoPago` (
  `id_metodoPago` INT NOT NULL AUTO_INCREMENT,
  `numero_tarjeta` VARCHAR(16) NOT NULL,
  `fecha_expiracion` VARCHAR(5) NOT NULL,
  `metodoPago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_metodoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`envio` (
  `id_envio` INT NOT NULL AUTO_INCREMENT,
  `hora_solicitud` TIME NOT NULL,
  `fecha_solicitud` DATE NOT NULL,
  `costo` INT NOT NULL,
  `nombre_destinatario` VARCHAR(200) NOT NULL,
  `correo_destinatario` VARCHAR(60) NOT NULL,
  `numeroCelular_destinatario` VARCHAR(10) NOT NULL,
  `id_metodoPago` INT NULL,
  `hora_entrega` TIME NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  `id_cliente` INT NULL,
  `id_lockerOrigen` INT NULL,
  `id_lockerDestino` INT NULL,
  `id_tipoEnvio` INT NOT NULL,
  `id_tamanio` INT NOT NULL,
  `id_estadoEnvio` INT NOT NULL,
  PRIMARY KEY (`id_envio`),
  UNIQUE INDEX `id_envio_UNIQUE` (`id_envio` ASC) VISIBLE,
  CONSTRAINT `metodoPago`
    FOREIGN KEY (`id_metodoPago`)
    REFERENCES `Lockerit`.`metodoPago` (`id_metodoPago`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `remitente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `Lockerit`.`Cliente` (`id_cliente`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `origen`
    FOREIGN KEY (`id_lockerOrigen`)
    REFERENCES `Lockerit`.`Locker` (`id_locker`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `destino`
    FOREIGN KEY (`id_lockerDestino`)
    REFERENCES `Lockerit`.`Locker` (`id_locker`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `tipoEnvio`
    FOREIGN KEY (`id_tipoEnvio`)
    REFERENCES `Lockerit`.`tipoEnvio` (`id_tipoEnvio`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `tamanio`
    FOREIGN KEY (`id_tamanio`)
    REFERENCES `Lockerit`.`Tamanio` (`id_tamanio`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `estadoEnvio`
    FOREIGN KEY (`id_estadoEnvio`)
    REFERENCES `Lockerit`.`estadoEnvio` (`id_estadoEnvio`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`qr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`qr` (
  `id_qr` INT NOT NULL AUTO_INCREMENT,
  `datos_qr` VARCHAR(60) NOT NULL,
  `estado_qr` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_qr`),
  UNIQUE INDEX `datos_qr_UNIQUE` (`datos_qr` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`taquilla_envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`taquilla_envio` (
  `id_taquilla-envio` INT NOT NULL AUTO_INCREMENT,
  `id_taquilla` INT NOT NULL,
  `id_envio` INT NOT NULL,
  `id_qr` INT NOT NULL,
  PRIMARY KEY (`id_taquilla-envio`),
  UNIQUE INDEX `id_taquilla-envio_UNIQUE` (`id_taquilla-envio` ASC) VISIBLE,
  CONSTRAINT `taquilla`
    FOREIGN KEY (`id_taquilla`)
    REFERENCES `Lockerit`.`Taquilla` (`id_taquilla`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `envio`
    FOREIGN KEY (`id_envio`)
    REFERENCES `Lockerit`.`envio` (`id_envio`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `qr`
    FOREIGN KEY (`id_qr`)
    REFERENCES `Lockerit`.`qr` (`id_qr`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`tipoReporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`tipoReporte` (
  `id_tipoReporte` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipoReporte` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_tipoReporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lockerit`.`reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lockerit`.`reporte` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `id_repartidor` INT NULL,
  `id_envío` INT NOT NULL,
  `id_tipoReporte` INT NOT NULL,
  PRIMARY KEY (`id_reporte`),
  CONSTRAINT `repartidor`
    FOREIGN KEY (`id_repartidor`)
    REFERENCES `Lockerit`.`Empleados` (`numeroEmpleado`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `envio`
    FOREIGN KEY (`id_envío`)
    REFERENCES `Lockerit`.`envio` (`id_envio`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `tipoReporte`
    FOREIGN KEY (`id_tipoReporte`)
    REFERENCES `Lockerit`.`tipoReporte` (`id_tipoReporte`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
